services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "8080:80"
    restart: unless-stopped

  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["npm","run","dev","--","--host"]
    volumes:
      - .:/app
    ports:
      - "5173:5173" # Vite default
