services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "8080:80"
    restart: unless-stopped

  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["npm","run","dev","--","--host"]
    ports:
      - "5173:5173"   # Vite
    environment:
      # Helpful for file watching inside containers
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      # ensure esbuild/rollup postinstall can run during image build (kept here for clarity)
      npm_config_ignore_scripts: "false"
    volumes:
      - .:/app                 # your source
      - /app/node_modules      # keep Linux node_modules in container (anonymous volume)
      # optional: cache vite deps between runs (Linux-only path inside container)
      - vite_cache:/app/node_modules/.vite

volumes:
  vite_cache:
