services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    ports:
      - "8080:80"
    restart: unless-stopped

  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    command: ["npm","run","dev","--","--host"]
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
      npm_config_ignore_scripts: "false"
    volumes:
      - .:/app
      - /app/node_modules
      - vite_cache:/app/node_modules/.vite

volumes:
  vite_cache:
