
export enum SharedStatus {
    ON_REVIEW = 'ON_REVIEW',
    ACTIVE = 'ACTIVE',
    INACTIVE = 'INACTIVE',
    PENDING = 'PENDING',
    SUSPENDED = 'SUSPENDED',
    CLOSED = 'CLOSED',
    UNDER_REVIEW = 'UNDER_REVIEW',
    TERMINATED = 'TERMINATED',
    DELETED = 'DELETED',
    ARCHIVED = 'ARCHIVED',
    BLOCKED = 'BLOCKED',
    FROZEN = 'FROZEN',
    DORMANT = 'DORMANT',
    SUSPENDED_FOR_VERIFICATION = 'SUSPENDED_FOR_VERIFICATION',
    SUSPENDED_FOR_COMPLIANCE = 'SUSPENDED_FOR_COMPLIANCE',
    SUSPENDED_FOR_SECURITY = 'SUSPENDED_FOR_SECURITY',
    SUSPENDED_FOR_FRAUD = 'SUSPENDED_FOR_FRAUD',
    SUSPENDED_FOR_ABUSE = 'SUSPENDED_FOR_ABUSE'
}